version: "3.8"
services:
  mysqldb:
    image: mysql:8
    ports:
      - 3307:3306
    restart: always
    environment:
      MYSQL_DATABASE: user_rental
      MYSQL_USER: leo
      MYSQL_PASSWORD: leo
      MYSQL_ROOT_PASSWORD: leo
  api:
    restart: always
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  